---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.0.2
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: true
    checksum: false
    download: true
    fetch: true
    git: false
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: true
app_desc: A command-line benchmarking tool
app_name: hyperfine
app_repo: https://github.com/sharkdp/hyperfine
app_type: standalone
app_website: https://github.com/sharkdp/hyperfine
archive_conf_path: ''
archive_conf_strip: 1
archive_enabled: true
archive_regex: \.tar\.gz$
checksum_enabled: false
custom_arch_enabled: true
custom_arch_yaml:
    aarch64*: aarch64
    armv5*: arm
    armv6*: arm
    armv7*: arm
    x86: x86_64
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_os_enabled: true
custom_os_yaml:
    darwin: apple-darwin
    linux: unknown-linux-musl
custom_require_commands: ''
download_url: https://github.com/sharkdp/hyperfine/releases/download/v{version}/hyperfine-v{version}-{arch}-{os}.tar.gz
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    hyperfine: bin/hyperfine
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-hyperfine
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-hyperfine.git
source_enabled: false
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
